# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Maypole
version:      1.7
version_from: lib/Maypole.pm
installdirs:  site
requires:
    Apache::Request:               0
    CGI::Untaint:                  0
    Class::DBI:                    0.96
    Class::DBI::AbstractSearch:    0
    Class::DBI::AsForm:            2.2
    Class::DBI::FromCGI:           0.94
    Class::DBI::Loader:            0.02
    Class::DBI::Loader::Relationship: 0
    Class::DBI::Pager:             0
    Class::DBI::Plugin::RetrieveAll: 0
    Template:                      0
    Template::Plugin::Class:       0
    UNIVERSAL::moniker:            0
    UNIVERSAL::require:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
